// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef ui_hpp
#define ui_hpp
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include "usbCommands.hpp"
#include "usbHelpers.hpp"
#include <FL/Fl_Group.H>
#include <FL/Fl_Value_Slider.H>
#include <FL/Fl_Button.H>

/**
   Main UI class
*/
class UserInterface {
public:
  UserInterface(MouseInfo info);
  Fl_Window *mainWindow;
  Fl_Value_Slider *redSlider;
  Fl_Value_Slider *greenSlider;
  Fl_Value_Slider *blueSlider;
  Fl_Button *applyButton;
private:
  inline void cb_applyButton_i(Fl_Button*, void*);
  static void cb_applyButton(Fl_Button*, void*);
  /**
     Metadata about the mouse we configure
  */
  MouseInfo mouseInfo; 
};
#endif
