// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef ui_hpp
#define ui_hpp
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include "usbCommands.hpp"
#include "usbHelpers.hpp"
#include <FL/Fl_Group.H>
#include <FL/Fl_Value_Slider.H>
#include <FL/Fl_Input_Choice.H>

/**
 Main UI class
*/
class UserInterface {
public:
  UserInterface(MouseInfo info);
  Fl_Window *mainWindow;
  Fl_Value_Slider *redSlider;
private:
  inline void cb_redSlider_i(Fl_Value_Slider*, void *);
  static void cb_redSlider(Fl_Value_Slider*, void *);
public:
  Fl_Value_Slider *greenSlider;
private:
  inline void cb_greenSlider_i(Fl_Value_Slider*, void*);
  static void cb_greenSlider(Fl_Value_Slider*, void*);
public:
  Fl_Value_Slider *blueSlider;
private:
  inline void cb_blueSlider_i(Fl_Value_Slider*, void*);
  static void cb_blueSlider(Fl_Value_Slider*, void*);
public:
  Fl_Input_Choice *profilePicker;
private:
  /**
   Metadata about the mouse we configure
  */
  MouseInfo mouseInfo; 
  /**
   The mouse configuration
  */
  G600Data mouseData[3]; 
};
#endif
